[phases.setup]
cmds = [
    "cd school && pip install -r requirements.txt",
    "cd school && python manage.py collectstatic --noinput"
]

[start]
cmd = "cd school && gunicorn school.wsgi:application"

[phases.build]
cmds = [
    "cd school && python manage.py migrate"
]
