
services:
  - type: web
    name: school-game
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn school.wsgi:application
    autoDeploy: true
    plan: free
