
services:
  - type: web
    name: school-game
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libjpeg-dev zlib1g-dev
      pip install -r requirements.txt
    startCommand: gunicorn school.wsgi:application
